import { StyleSheet } from "react-native";

const puntosStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  safe: {
    flex: 1,
  },
  iconCard: {
    backgroundColor: "#fff",
    width: 45,
    height: 45,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 4,
    marginTop: 25,
  },
  iconCards: {
    backgroundColor: "#fff",
    width: 45,
    height: 45,
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 10,
    shadowColor: "#000",
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 10,
    marginTop: 25,
  },
  header: {
    height: 90,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    justifyContent: "space-between",
  },
  headerTitle: {
    fontSize: 22,
    color: "#fff",
    fontWeight: "bold",
    textAlign: "center",
    marginTop: 25,
    marginLeft: 10,
  },
  margen: {
    paddingHorizontal: 20,
    flex: 1,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E5E5E5",
    borderRadius: 30,
    paddingHorizontal: 15,
    marginBottom: 20,
    margin: 12,
  },
  cardMenu: {
    backgroundColor: "#2680B2",
    borderRadius: 50,
    padding: 15,
    marginBottom: 20,
    flexDirection: "row",
    alignItems: "center",
  },
  input: {
    flex: 1,
    height: 50,
    marginLeft: 10,
    color: "#000",
  },
  filtroContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 0,
  },
  filtroLabel: {
    color: "#fff",
    marginRight: 10,
  },
  filtroButton: {
    backgroundColor: "#0076A7",
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 50,
    marginRight: 10,
    marginTop: 5,
    borderColor: "#FFFFFF",
    borderWidth: 1,
  },
  filtroActivo: {
    backgroundColor: "#fff",
  },
  filtroTextActivo: {
    color: "#0076A7",
    fontWeight: "500",
  },
  botonActivo: {
    color: "#fff",
  },
  listTitle: {
    color: "#fff",
    fontWeight: "bold",
    marginBottom: 10,
    textAlign: "center",
  },
  card: {
    backgroundColor: "#E5E5E5",
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
  },
  estadoBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 15,
    marginBottom: 10,
  },
  activo: {
    backgroundColor: "#4CAF50",
  },
  pendiente: {
    backgroundColor: "#FF454C",
  },
  cerrado: {
    backgroundColor: "#979b9cff",
  },
  estadoText: {
    color: "#fff",
    fontWeight: "bold",
  },
  estadoAbierto: {
    color: "#fff",
    fontWeight: "bold",
  },
  codigo: {
    position: "absolute",
    right: 20,
    top: 20,
    fontWeight: "bold",
  },
  info: {
    marginBottom: 5,
    color: "#333",
  },
  buttonContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    height: 30,
    width: 90,
  },
  MenuText: {
    color: "#fff",
    fontSize: 12,
    textAlign: "center",
  },
  menuTextActivo: {
    color: "#0076A7",
    fontWeight: "bold",
  },
  menuActivo: {
    backgroundColor: "#FFFFFF",
  },
  MenuButton: {
    flex: 1,
    backgroundColor: "#0076A7",
    paddingVertical: 5,
    paddingHorizontal: 5,
    borderRadius: 50,
    marginRight: 4,
    borderColor: "#fff",
    borderWidth: 1,
    alignItems: "center",
    marginLeft: 4,
    justifyContent: "center",
  },
  TextResul: {
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
    marginTop: 12,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
  },
  emptyTitle: {
    marginTop: 15,
    fontSize: 16,
    fontWeight: "600",
    color: "#fff",
  },
  emptySubtitle: {
    marginTop: 5,
    fontSize: 14,
    color: "#fff",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalCard: {
    width: "85%",
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 20,
    elevation: 10,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 20,
    textAlign: "center",
  },
  modalOption: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderColor: "#eee",
  },
  modalOptionText: {
    fontSize: 16,
    marginLeft: 15,
  },
  modalCancel: {
    marginTop: 20,
    backgroundColor: "#0076A7",
    paddingVertical: 12,
    borderRadius: 10,
  },
  modalCancelText: {
    color: "#fff",
    textAlign: "center",
    fontWeight: "bold",
  },
  avatarContainer: {
    width: 45,
    height: 45,
    borderRadius: 50,
    backgroundColor: "#fff",
    justifyContent: "center",
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 10,
    overflow: "hidden",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
  },
  avatarInitial: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#0076A7",
  },
  ononlineDot: {
    position: "absolute",
    bottom: 3,
    right: 3,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#22C55E",
    borderWidth: 2,
    borderColor: "#fff",
  },
  statusCircle: {
    width: 14,
    height: 14,
    borderRadius: 7,
    position: "absolute",
    bottom: 5,
    right: 5,
    borderWidth: 2,
    borderColor: "#fff",
  },

  statusOnline: {
    backgroundColor: "#22c55e",
  },

  statusBusy: {
    backgroundColor: "#f97316", 
  },

  statusAway: {
    backgroundColor: "#9ca3af",
  },
});

export default puntosStyles;
